### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by zxhycxq** [cqm1994617/react-mobx-cart#1]
全选的时候，取消某一个列，然后点击删除，这时候剩下的列表其实是全选的，但是顶部的全选按钮却没有选中

**Comment by jianpiao** [comment]
//解决办法
//  遍历列表的每一项 判断所有都为true的话就 让 checkedAll = true 反之
    this.list.every((item) => item.checked === true) ? this.checkedAll = true : this.checkedAll = false;
