### ISSUE TITLE
npm install 报错

### ISSUE THREAD

**Issue by hqzh** [cqm1994617/react-mobx-cart#2]
npm install 报错

**Comment by cqm1994617** [comment]
方便贴一下具体的报错吗？

**Comment by hqzh** [comment]
![npm1](https://user-images.githubusercontent.com/26128706/40522342-0012d962-6003-11e8-93a1-c333808a2644.png)
![npm](https://user-images.githubusercontent.com/26128706/40522347-04d1d2dc-6003-11e8-8b6c-70bcb44b776e.png)
![npm2](https://user-images.githubusercontent.com/26128706/40522349-0860fdce-6003-11e8-8fe7-e0832e4501bc.png)

**Comment by hqzh** [comment]
@cqm1994617 以上
